# Generated by Django 3.2.5 on 2021-07-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourapp', '0002_delete_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPlace',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('Place', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('Inside_Places', models.CharField(max_length=300)),
                ('Persons', models.PositiveIntegerField()),
                ('Image', models.FileField(upload_to='files')),
                ('Details', models.TextField()),
                ('Marked_Price', models.PositiveIntegerField()),
                ('Confirm_Price', models.PositiveIntegerField()),
            ],
        ),
    ]
