# Generated by Django 3.2.5 on 2021-07-30 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0007_auto_20210730_0946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminModel',
        ),
        migrations.DeleteModel(
            name='TourPlace',
        ),
    ]
