# Generated by Django 3.2.5 on 2021-07-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourapp', '0008_auto_20210730_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourPlace',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('Place', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField()),
                ('Inside_Places', models.CharField(max_length=300)),
                ('Persons', models.CharField(max_length=100)),
                ('Image', models.FileField(upload_to='files')),
                ('Details', models.TextField()),
                ('Marked_Price', models.PositiveIntegerField()),
                ('Confirm_Price', models.PositiveIntegerField()),
            ],
        ),
    ]
