# Generated by Django 3.2.5 on 2021-07-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0009_adminmodel_tourplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourplace',
            name='Place',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tourplace',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
